name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  KUBECONFIG_FILE: 'kubeconfig.yml'
  AWS_REGION: 'us-east-1'
  AWS_EKS_CLUSTER_NAME: 'eks-keycloak'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install and configure AWS CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Install and configure kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Get Access to EKS Cluster
      run: |
        aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --kubeconfig ${{ env.KUBECONFIG_FILE }} --region ${{ env.AWS_REGION }} --name ${{ env.AWS_EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/ --kubeconfig=${{ env.KUBECONFIG_FILE }}
